version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine
  
  discountdb:
    image: postgres
  
  pgadmin:
    image: dpage/pgadmin4

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile
  
  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.GRPC/Dockerfile
  
  prometheus:
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
      args:
        version: 1
    image:  ${DOCKER_REGISTRY-}prometheus
    restart: always
    ports:
      - 9090:9090

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: ${DOCKER_REGISTRY-}grafana
    restart: always
    ports:
      - 3000:3000
  
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: ./fluentd
    image: fluentd
    ports:
      - 24224:24224
    depends_on:
      - catalogdb
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers
      - ./fluentd/configurations:/fluentd/etc
      - ./fluentd/logs:/output
    logging:
      driver: local

    

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data: