global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "Basket.API"
    metrics_path: /metrics
    static_configs:
      - targets: ["basket.api:80"]
        labels:
          alias: "basketapi"